<center><img src="https://www.python.org/static/img/python-logo.png" title="Python Logo"/></center>

<blockquote>
<center><h2 style="font-family:Lucida Console">Ciência de Dados com Python</h2></center>
</blockquote>

```python 
print('Felipe Soares dos Santos Silveira, GES | 2025.2')
```

<hr>

> <center><h3 style="font-family:Lucida Console">Capítulo 4</h3></center>

<div style="display: flex; justify-content: center; gap: 10px;">
  <img src="https://raw.githubusercontent.com/Felipe-SSS/C11/main/images/Cap4_Exercicios_1.png" title="Exercícios (Parte 1)" width="600"/>
  <img src="https://raw.githubusercontent.com/Felipe-SSS/C11/main/images/Cap4_Exercicios_2.png" title="Exercícios (Parte 2)" width="607"/>
</div>

> <h4 style="font-family:Lucida Console">Exercício 1</h4>

In [ ]:
import numpy as np

array_1s = np.ones(8, dtype=int)

random = np.random.default_rng(13)
array_0a9 = random.integers(low=0, high=10, size=8)

array_soma = array_1s + array_0a9

array_soma

array([ 9,  9,  9,  9,  1,  9, 10,  3], dtype=int64)

In [36]:
if array_soma.sum() >= 40:
    array_soma = array_soma.reshape(4,2)
else:
    array_soma = array_soma.reshape(2,4)

array_soma

array([[ 9,  9],
       [ 9,  9],
       [ 1,  9],
       [10,  3]], dtype=int64)

> <h4 style="font-family:Lucida Console">Exercício 2</h4>

In [41]:
import numpy as np

pares_0_ate_50 = np.arange(0, 51, 2, dtype=int)
pares_100_ate_50 = np.arange(100, 50, -2, dtype=int)

concatenadas = np.concatenate((pares_0_ate_50, pares_100_ate_50))

In [44]:
concatenadas.sort()
concatenadas

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

> <h4 style="font-family:Lucida Console">Exercício 3</h4>

In [62]:
import numpy as np

field = np.zeros(shape=(2,2), dtype=int)

In [63]:
rand_row = np.random.randint(field.shape[0])
rand_col = np.random.randint(field.shape[1])

field[rand_row][rand_col] = 1

field

array([[1, 0],
       [0, 0]])

In [73]:
flag = True
count = 0

In [74]:
while flag and count < 3:
    
    row = int(input("Insira a linha alvo: "))
    col = int(input("Insira a coluna alvo: "))
    
    count += 1
    
    if field[row][col] == 1:
        print("Game over! :( Try again!")
        flag = False

if count == 3:
    print("Congratulations! You beat the game! :)")

Congratulations! You beat the game! :)


> <h4 style="font-family:Lucida Console">Exercício 4</h4>

In [98]:
import numpy as np

np.random.seed(700)

rand_rows = np.random.randint(low=1, high=10)
rand_cols = np.random.randint(low=1, high=10)

array = np.zeros(shape=(rand_rows, rand_cols))

In [101]:
soma = array.shape[0] * array.shape[1]

In [102]:
if soma % 2 == 0:
    print("Unidimensional com número par de elementos.")
else:
    print("Unidimensional com número ímpar de elementos.")

Unidimensional com número par de elementos.


> <h4 style="font-family:Lucida Console">Exercício 5</h4>

In [ ]:
import numpy as np
np.random.seed(10)
random_values = np.random.randint(low=1, high=50, size=(4,4))   

In [121]:
row_means = np.zeros(shape=4)
for i in range(random_values.shape[0]):
    row_means[i] = random_values[i, :].mean()
    print(row_means[i])

print(row_means.max())

25.25
34.25
11.25
19.25
34.25


In [116]:
col_means = np.zeros(shape=4)
for j in range(random_values.shape[1]):
    col_means[j] = random_values[:, j].mean()
    print(col_means[j])
    
print(col_means.max())

22.0
22.0
27.25
18.75
27.25


In [127]:
unique, counts = np.unique(random_values, return_counts=True)

result = unique[counts == 2]

print(result)

[ 9 17]
